### ISSUE TITLE
Arreglar pregunta incorrecta

### ISSUE THREAD

**Issue by alvarosperez** [Arquisoft/Trivial5a#12]
https://github.com/Arquisoft/Trivial5a/blob/a58f4e4b0e4b5cff728498ac0e0d3d7cbc76b78d/extract/src/main/java/es/uniovi/asw/data/preguntas.gift#L87

Suiza en realidad no tiene capital. En Berna está solo la sede parlamentaria.

De la wikipedia: https://en.wikipedia.org/wiki/Switzerland#cite_note-fedcit-2
Bern is referred to as "federal city" ([German](https://en.wikipedia.org/wiki/German_language): Bundesstadt, [French](https://en.wikipedia.org/wiki/French_language): ville fédérale, [Italian](https://en.wikipedia.org/wiki/Italian_language): città federale). Swiss law does not designate a capital as such, [b](https://en.wikipedia.org/wiki/Switzerland#cite_ref-national-survey_7-1)ut the federal parliament and government are in Bern, while other federal institutions, su[c](https://en.wikipedia.org/wiki/Switzerland#cite_ref-national-survey_7-2)h as the fe[d](https://en.wikipedia.org/wiki/Switzerland#cite_ref-national-survey_7-3)eral courts, are in other cities (Bellinzona, Lausanne, Luzern, Neuchâtel, St. Gallen a.o.).

**Comment by labra** [comment]
Gracias por el issue. No obstante, este repositorio de arquitectura del software es de cursos anteriores y ya no se mantiene de forma activa. Voy a proceder a archivar el repositorio.
